@isTest
public class EmployeeWiseTarget_Test {
    @isTest
    static void testRollupTargetAmountEmployeeWiseTarget() {
        // Create a Fiscal Year record
        Fiscal_Year__c fy = new Fiscal_Year__c(
            Name = 'FY 2024',
            FY_Start_Date__c = Date.newInstance(2025, 1, 1),
            FY_End_Date__c = Date.newInstance(2026, 12, 31)
            
        );
        insert fy;
        
        
        // Create an Employee Wise Target record
        Employee_Wise_Target__c target = new Employee_Wise_Target__c(
            Employee__c  = UserInfo.getUserId(),
            Fiscal_Year__c = fy.Id,
            Target_Quantity__c = 10,
            Target_Amount__c = 1000
        );
        insert target;
        
        List<sObject> newRecords = new List<sObject>{target};
            Map<Id, sObject> oldMap = new Map<Id, sObject>{
                target.Id => new Employee_Wise_Target__c(
                    Id = target.Id,
                    Target_Quantity__c = 100,
                    Target_Amount__c = 10000
                )  
                    };                                                        
                        
                        Test.startTest();
        TargetAllInOneTriggerHandler.rollupTargetAmount(newRecords, oldMap, 'EmployeeWiseTarget');
        Test.stopTest();
        
    }
    
    @isTest
    static void testRollupTargetAmountEmployeeWiseProductTarget() {
        
        Fiscal_Year__c fy = new Fiscal_Year__c(
            Name = 'FY 2024',
            FY_Start_Date__c = Date.newInstance(2025, 1, 1),
            FY_End_Date__c = Date.newInstance(2026, 12, 31)
            
        );
        insert fy;
        
        Product2 prod = new Product2();
        prod.Name='VOXCO ZINC PHOSPHATE ';
        prod.Family = 'Anti-Corrosive';
        insert prod;
        
        // Create an Employee Wise Product Target record
        Employee_Wise_Product_Target__c productTarget = new Employee_Wise_Product_Target__c(
            Employee__c = UserInfo.getUserId(),
            Product__c = prod.Id,
            Fiscal_Year__c = fy.Id,
            
            Target_Quantity__c = 100,
            Target_Amount__c=1200
        );
        insert productTarget;
        
        List<sObject> newRecords = new List<sObject>{productTarget};
            Map<Id, sObject> oldMap = new Map<Id, sObject>{
                productTarget.Id => new Employee_Wise_Product_Target__c(
                    Id = productTarget.Id,
                    Target_Quantity__c = 100,
                    Target_Amount__c=1000
                )
                    };
                        
                        Test.startTest();
        TargetAllInOneTriggerHandler.rollupTargetAmount(newRecords, oldMap, 'EmployeeWiseProductTarget');
        
        Test.stopTest();
        
    }
    
    @isTest
    static void createMonthlyTargetEntriesTest() {
        
        Fiscal_Year__c fy = new Fiscal_Year__c(
            Name = 'FY 2024',
            FY_Start_Date__c = Date.newInstance(2025, 1, 1),
            FY_End_Date__c = Date.newInstance(2026, 12, 31)
            
        );
        insert fy;
        
        Account acc = new Account(Name = 'Account ');
        
        // Create an Employee Wise Account Target record
        Employee_Wise_Account_Target__c accountTarget = new Employee_Wise_Account_Target__c(
            Employee__c =UserInfo.getUserId(),
            Account__c = acc.Id,
            Fiscal_Year__c = fy.Id,
            Target_Quantity__c = 100,
            Target_Amount__c = 1200
        );
        insert accountTarget;
        
        
        List<sObject> newRecords = new List<sObject>{accountTarget};
            Map<Id, sObject> oldMap = new Map<Id, sObject>{
                accountTarget.Id => new Employee_Wise_Account_Target__c(
                    Id = accountTarget.Id,
                    Target_Quantity__c = 100,
                    Target_Amount__c=1000
                )
                    }; 
                        
                        Test.startTest();
        TargetAllInOneTriggerHandler.createMonthlyTargetEntries(newRecords);
        
        Test.stopTest();
        
    }
    
     @isTest
    static void updateMonthlyTargetEntriesTest() {
        
        Fiscal_Year__c fy = new Fiscal_Year__c(
            Name = 'FY 2024',
           FY_Start_Date__c = Date.newInstance(2025, 1, 1),
            FY_End_Date__c = Date.newInstance(2026, 12, 31));
        
        insert fy;
        // Create an Employee Wise Target record
        Employee_Wise_Target__c target = new Employee_Wise_Target__c(
            Employee__c  = UserInfo.getUserId(),
            Fiscal_Year__c = fy.Id,
            Target_Quantity__c = 10,
            Target_Amount__c = 1000
        );
        insert target;
        
        List<sObject> newRecords = new List<sObject>{target};
            
        Map<Id, sObject> newMap = new Map<Id, sObject>(newRecords);
        
        Map<Id, sObject> oldMap = new Map<Id, sObject>{
            target.Id => new Employee_Wise_Target__c(
                Id = target.Id,
                Target_Quantity__c = 100,
                Target_Amount__c = 10000
            )  
         }; 
                    
        Test.startTest();
        TargetAllInOneTriggerHandler.updateMonthlyTargetEntries(newRecords, oldMap,newMap, 'EmployeeWiseTarget');
        Test.stopTest();
        
        
    }    
   
    @isTest
    static void shareRecordWithUserTest() {
        List<Employee_Wise_Target__c> employeeTargets = new List<Employee_Wise_Target__c>();
        List<Employee_Wise_Product_Target__c> productTargets = new List<Employee_Wise_Product_Target__c>();
        List<Employee_Wise_Account_Target__c> accountTargets = new List<Employee_Wise_Account_Target__c>();

            Product2 prod = new Product2();
            prod.Name='VOXCO ZINC PHOSPHATE ';
            prod.Family = 'Anti-Corrosive';
            insert prod;
            Employee_Wise_Target__c ewt = new Employee_Wise_Target__c(
                
                Target_Quantity__c = 100,
                Target_Amount__c = 1000,
                Employee__c = UserInfo.getUserId() 
            );
            Employee_Wise_Product_Target__c ewpt = new Employee_Wise_Product_Target__c(
                Product__c= prod.Id,
                Target_Quantity__c = 200,
                Target_Amount__c = 2000,
                Employee__c = UserInfo.getUserId()
            );
            Account acc = new Account(Name = 'Test Account');
            Employee_Wise_Account_Target__c ewat = new Employee_Wise_Account_Target__c(
                Account__c=acc.Id,
                Target_Quantity__c = 300,
                Target_Amount__c = 3000,
                Employee__c = UserInfo.getUserId()
            );
            
        insert employeeTargets;
        insert productTargets;
        insert accountTargets;
        
        List<sObject> newRecords = new List<sObject>();
        newRecords.addAll(employeeTargets);
        newRecords.addAll(productTargets);
        newRecords.addAll(accountTargets);
        

        Test.startTest();
        TargetAllInOneTriggerHandler.shareRecordWithUser(newRecords, null );
        Test.stopTest();
        
        
    }
}